Add graph css
paion-data/Messier-61 pull request #16
Opened 2023-03-17 07:51 UTC by Xxy1016

Changelog
---------

### Added
修改画布的CSS样式
### Changed

### Deprecated

### Removed

### Fixed

### Security

Checklist
---------

* [ ] Test
* [ ] Self-review
* [ ] Documentation

2023-03-17 09:42 UTC, QubitPi requested changes

2023-03-17 09:42 UTC, QubitPi commented on packages/messier-61-graph/GraphDecorator.ts
> +  if (label.length >= 1 && label.length < 5) {
label.length < 5

2023-03-17 09:43 UTC, QubitPi approved these changes

2023-03-17 09:45 UTC, merged

2023-03-18 05:24 UTC, RafaellahozlaveloyPAYAN9395 commented on packages/messier-61-graph/D3Graph/D3Graph.tsx
> +      //   .text((d) => textLable(d.name));
NEFRITIS