Add link
paion-data/Messier-61 pull request #51
Opened 2023-02-16 10:09 UTC by Xxy1016

Changelog
---------

### Added

- Added html link

### Changed

### Deprecated

### Removed

### Fixed

### Security

Checklist
---------

- [ ] Test
- [ ] Self-review
- [ ] Documentation

2023-02-16 14:22 UTC, QubitPi requested changes
I'm very happy that you added unit tests to this PR! 💯 Just some polishing left there and we are ready to merge this PR.

2023-02-16 14:22 UTC, QubitPi commented on src/components/Home/Home.test.tsx
> +expect(linkToTest.getAttribute("href")).toMatchInlineSnapshot();
👍🏻 for using `screen.getByRole("link", { name: /link to test/i });`, **very brilliant**!

Adding links to "GitHub" and "Help" is a very important feature and, therefore, deserves its own unit test. A unit test in React (or JavaScript in general) is described by a [`test` macro](https://jestjs.io/docs/getting-started) and we need to test both "GitHub" and "Help" links.

I saw you also have **snapshot testing** there (`toMatchInlineSnapshot`) and this is indeed very nice. Snapshot testing though does have it's downside in some cases. _In general, Messier-61 do not use snapshot testing_

Putting everything together, I recommend enhancing the code to become something like the following:

```typescript
test("GitHub and Help buttons point to the expected locations", () => {
  render(
    <BrowserRouter>
      <Home />
    </BrowserRouter>
  );

  const githubLink = screen.getByRole("link", { name: /GitHub/i });
  expect(githubLink.getAttribute("href")).toBe('https://github.com/paion-data/Messier-61');

  const helpLink = screen.getByRole("link", { name: /Help/i });
  expect(helpLink.getAttribute("href")).toBe('https://paion-data.github.io/Messier-61/');
});
```

2023-02-17 01:45 UTC, Xxy1016 commented on src/components/Home/Home.css
> +
大概是因为我格式化了一下代码 所以自动添加了一行空格

2023-02-17 01:46 UTC, Xxy1016 commented on src/components/Home/Home.css
> +  text-decoration: none;
因为HTML里的超链接会自动带有下划线样式 所以在CSS中取消了下划线

2023-02-17 03:08 UTC, QubitPi commented on src/components/Home/Home.css
> +  text-decoration: none;
Ok

2023-02-17 06:39 UTC, QubitPi approved these changes

2023-02-17 06:54 UTC, merged