implementation Visualization View Module
paion-data/Messier-61 pull request #84
Opened 2023-06-27 10:12 UTC by Xxy1016

Changelog
---------

### Added

### Changed

### Deprecated

### Removed

### Fixed

### Security

Checklist
---------

* [ ] Test
* [ ] Self-review
* [ ] Documentation

2023-06-27 13:06 UTC, QubitPi requested changes
嗯，方向完全正确，下一步就是搞定 ViausalizationView，细节上，我们一步一步来，详见 comments，很好

2023-06-27 13:06 UTC, QubitPi commented on package.json
> +    "suber": "^5.0.1"
从你的代码来看，你应该是已经理解了 suber Bus 在这里的作用，目前暂时不需要用到，可以先删除

2023-06-27 13:06 UTC, QubitPi commented on packages/messier-61-graph/src/visualization-view/custom.d.ts
这个文件是做什么用的 🤔 ?

2023-06-28 04:15 UTC, Xxy1016 commented on packages/messier-61-graph/src/visualization-view/custom.d.ts
这个是因为不存在@types/suber包，所以需要一个声明文件才能使用suber Bus，现在不需要，已经删除了

2023-06-28 05:55 UTC, QubitPi approved these changes
👍🏻

2023-06-28 05:56 UTC, QubitPi commented on packages/messier-61-graph/src/visualization-view/custom.d.ts
OK

2023-06-28 06:14 UTC, merged