Realize the linkage between Editor and VisualizationView
paion-data/Messier-61 pull request #85
Opened 2023-06-28 10:17 UTC by Xxy1016

Changelog
---------

### Added

### Changed

### Deprecated

### Removed

### Fixed

### Security

Checklist
---------

* [ ] Test
* [ ] Self-review
* [ ] Documentation

2023-06-28 14:49 UTC, QubitPi requested changes
👍🏻 Very nice. 留了一些 minor comments

2023-06-28 14:49 UTC, QubitPi commented on packages/messier-61-graph/src/visualization-view/VisualizationView.tsx
> +import { Bus } from "suber";
这里是什么原因需要用到 `suber` 呢？

2023-06-28 14:49 UTC, QubitPi commented on packages/messier-61-graph/src/editor-graph/EditorGraph.tsx
> +export function EditorGraph(): JSX.Element {
`EditorGraph` 从名字上有点难想到是做图组件，建议将其改成 `GraphBroser`（包括相关组件）

2023-06-29 01:17 UTC, Xxy1016 commented on packages/messier-61-graph/src/visualization-view/VisualizationView.tsx
> +import { Bus } from "suber";
目前不需要，已经删掉了

2023-06-29 01:23 UTC, QubitPi commented on packages/messier-61-graph/src/editor-graph/EditorGraph.tsx
> +export function EditorGraph(): JSX.Element {
`GraphBrowser`

2023-06-29 01:34 UTC, QubitPi approved these changes

2023-06-29 01:34 UTC, merged